#!/usr/bin/env node
'use strict';

const request = require('superagent');
const method = process.argv[2] || 'GET';
const path = process.argv[3] || '';

request(method, `http://localhost:9200/${path}`)
  .end((err, res) => {
    if (err && !res) {
      throw err;
    }
    console.log(res.statusCode, res.body);
  });
